"""
execution/reconciler.py
───────────────────────
WalletReconciler — compares on-chain reality against what the bot believes.

Why this exists
───────────────
Every serious fault of 2026-09-05/06 was invisible in the logs and obvious in
the wallet:

  * guards logged "expired unfilled" 35 times while the wallet spent 27 pUSD
  * a bundle was declared dead 208 ms after placement and its orders kept
    filling for four minutes afterwards
  * fills were credited to bundles that never opened, and positions those
    bundles had never bought were sold to "unwind" them

In every case the bot's own account of events was internally consistent and
completely wrong. No amount of log-reading catches that, because the logs are
generated by the same broken belief. The only thing that can catch it is a
comparison against something the bot does not control: the chain.

The invariant
─────────────
Inventory must not change while the bot believes it has nothing open.

`open_positions` is the circuit breaker's count of live exposure. When it is
zero, no guard is watching anything and no execution is in flight, so nothing
the bot did should be able to move share balances. If they move anyway, some
order escaped supervision — which is precisely the leak that cost 29 pUSD.

Deliberately not clever. It does not try to attribute fills or reprice
positions; mark-to-market drift is ignored entirely because prices move for
reasons that have nothing to do with us. It watches share COUNTS, which only
change when someone trades.

Nothing here trades. It reads, compares, and shouts.
"""

from __future__ import annotations

import asyncio
import logging
import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.clob_client import PolyClient
    from risk.circuit_breaker import CircuitBreaker
    from telemetry.telegram import TelegramNotifier

logger = logging.getLogger(__name__)

RECONCILE_POLL_S: float = float(os.environ.get("RECONCILE_POLL_S", 120.0))

# Share moves below this are rounding noise, not a trade.
_SHARE_EPS: float = 0.01




class WalletReconciler:
    """
    Periodically checks that on-chain inventory only moves when the bot thinks
    it is trading.  Read-only: it never places or cancels an order.
    """

    def __init__(
        self,
        client:   "PolyClient",
        breaker:  "CircuitBreaker",
        notifier: "TelegramNotifier",
        poll_s:   float = RECONCILE_POLL_S,
    ) -> None:
        self._client   = client
        self._breaker  = breaker
        self._notifier = notifier
        self._poll     = max(10.0, poll_s)
        self._prev: dict[str, float] | None = None
        self._prev_cash: float | None = None
        self.unexplained_events: int = 0
        # Settlements AutoRedeemer has announced but the snapshot has not yet
        # seen. Consumed on match, so a second unexplained move still alerts.
        self._redeemed: list[str] = []
        logger.info("WalletReconciler init | poll=%.0fs", self._poll)

    # ──────────────────────────────────────────────────────────────────────────

    def note_redemption(self, title: str) -> None:
        """
        AutoRedeemer announcing a settlement it has just performed.

        Titles are matched loosely because the reconciler keys positions by a
        truncated title while the redeemer works in condition IDs; a prefix
        match is enough to tell a settlement from a mystery.
        """
        self._redeemed.append(str(title)[:40])

    def _claim_redemption(self, key: str) -> bool:
        """Consume a pending announcement matching this position, if any."""
        head = key.split("|")[0].strip()[:40]
        for i, t in enumerate(self._redeemed):
            if t and (t.startswith(head[:24]) or head.startswith(t[:24])):
                del self._redeemed[i]
                return True
        return False

    async def _snapshot(self) -> "tuple[dict[str, float], float] | None":
        rows = await self._client.open_positions_detail()
        if rows is None:
            return None
        cash = await self._client.collateral_balance()
        if cash is None:
            return None
        held = {
            f"{r.get('title','')[:40]}|{r.get('outcome','')}": float(r.get("size") or 0.0)
            for r in rows
        }
        return held, float(cash)

    async def check_once(self) -> "dict | None":
        """
        One comparison. Returns a report dict when inventory moved with nothing
        open, else None.
        """
        snap = await self._snapshot()
        if snap is None:
            logger.debug("WalletReconciler | snapshot unavailable — skipping")
            return None
        held, cash = snap

        if self._prev is None:
            self._prev, self._prev_cash = held, cash
            logger.info(
                "WalletReconciler | baseline: %d position(s), cash=%.4f",
                len(held), cash,
            )
            # Inventory that exists before any bundle is watched is UNMANAGED.
            # The guards only resolve bundles they registered themselves, and
            # their watch list is in memory, so it is empty after every restart.
            # Anything already held is therefore nobody's: no guard will ever
            # flatten it, complete it, or even notice it. That is how the
            # positions left by the 2026-09-05 leak came to sit untouched for
            # 37 hours while the bot happily opened and closed new bundles
            # around them.
            #
            # Adopting them automatically is not safe — the original bundle
            # structure is gone, so we cannot know what they were meant to hedge
            # or at what price. Say so instead, and let a human decide.
            if held:
                detail = ", ".join(f"{k} {v:.2f}" for k, v in sorted(held.items()))
                logger.warning(
                    "WalletReconciler | %d UNMANAGED position(s) held at "
                    "startup — no guard is watching these and none will: %s",
                    len(held), detail,
                )
                await self._notifier.notify(
                    f"⚠️ {len(held)} pozíció felügyelet nélkül\n{detail}\n"
                    "Ezeket egyik guard sem figyeli — nem fogja se kiegészíteni, "
                    "se lezárni. Kézi döntést igényelnek."
                )
            return None

        moves = {
            k: round(held.get(k, 0.0) - self._prev.get(k, 0.0), 4)
            for k in set(held) | set(self._prev)
        }
        moves = {k: v for k, v in moves.items() if abs(v) > _SHARE_EPS}
        cash_delta = round(cash - (self._prev_cash or cash), 4)
        self._prev, self._prev_cash = held, cash

        if not moves:
            return None

        # A resolution is not an escape. When a market settles, AutoRedeemer
        # redeems the position: the shares go to zero and the cash rises. That
        # is the system working, and on 2026-09-08 it was reported as a fault —
        #
        #   RECONCILE | inventory moved with NOTHING open — an order escaped
        #   supervision | cash +20.2900 | Will Maura Sullivan ... |No -20.29
        #
        # A false alarm here is expensive in a way that is easy to miss: this is
        # the only check that catches a real leak, and an alert that cries wolf
        # stops being read.
        #
        # Redemptions are ANNOUNCED rather than inferred. Inferring them from
        # the cash delta works only when nothing else happened in the window: a
        # settlement of +20.29 alongside a purchase of -6.96 nets to +13.33 and
        # matches neither, so the real escape and the expected settlement would
        # both be misread. AutoRedeemer knows exactly what it redeemed.
        for title in list(moves):
            if moves[title] >= 0:
                continue
            if not self._claim_redemption(title):
                continue
            logger.info(
                "WalletReconciler | %s settled and was redeemed "
                "(%+.2f shares) — expected",
                title, moves[title],
            )
            del moves[title]
        if not moves:
            return None

        open_positions = int(self._breaker.status_dict().get("open_positions", 0))
        if open_positions > 0:
            # Normal: something is in flight and is expected to move inventory.
            logger.debug(
                "WalletReconciler | %d move(s) with %d position(s) open — expected",
                len(moves), open_positions,
            )
            return None

        # Inventory moved while the bot believed it had nothing open.
        self.unexplained_events += 1
        report = {
            "moves": moves,
            "cash_delta": cash_delta,
            "open_positions": open_positions,
        }
        detail = ", ".join(f"{k} {v:+.2f}" for k, v in sorted(moves.items()))
        logger.error(
            "RECONCILE | inventory moved with NOTHING open — an order escaped "
            "supervision | cash %+.4f | %s",
            cash_delta, detail,
        )
        await self._notifier.notify(
            "⚠️ RECONCILE — inventory changed while the bot had nothing "
            f"open.\ncash {cash_delta:+.4f} pUSD\n{detail}\n"
            "An order filled outside guard supervision; check for resting orders."
        )
        return report

    async def run(self) -> None:
        logger.info("WalletReconciler started | poll=%.0fs", self._poll)
        try:
            while True:
                await asyncio.sleep(self._poll)
                try:
                    await self.check_once()
                except asyncio.CancelledError:
                    raise
                except Exception as exc:  # noqa: BLE001
                    logger.error("WalletReconciler check failed: %s", exc)
        except asyncio.CancelledError:
            logger.info("WalletReconciler stopped")
            raise
