"""
execution/reconciler.py
───────────────────────
WalletReconciler — compares on-chain reality against what the bot believes.

Why this exists
───────────────
Every serious fault of 2026-09-05/06 was invisible in the logs and obvious in
the wallet:

  * guards logged "expired unfilled" 35 times while the wallet spent 27 pUSD
  * a bundle was declared dead 208 ms after placement and its orders kept
    filling for four minutes afterwards
  * fills were credited to bundles that never opened, and positions those
    bundles had never bought were sold to "unwind" them

In every case the bot's own account of events was internally consistent and
completely wrong. No amount of log-reading catches that, because the logs are
generated by the same broken belief. The only thing that can catch it is a
comparison against something the bot does not control: the chain.

The invariant
─────────────
Inventory must not change while the bot believes it has nothing open.

`open_positions` is the circuit breaker's count of live exposure. When it is
zero, no guard is watching anything and no execution is in flight, so nothing
the bot did should be able to move share balances. If they move anyway, some
order escaped supervision — which is precisely the leak that cost 29 pUSD.

Deliberately not clever. It does not try to attribute fills or reprice
positions; mark-to-market drift is ignored entirely because prices move for
reasons that have nothing to do with us. It watches share COUNTS, which only
change when someone trades.

Nothing here trades. It reads, compares, and shouts.
"""

from __future__ import annotations

import asyncio
import logging
import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.clob_client import PolyClient
    from risk.circuit_breaker import CircuitBreaker
    from telemetry.telegram import TelegramNotifier

logger = logging.getLogger(__name__)

RECONCILE_POLL_S: float = float(os.environ.get("RECONCILE_POLL_S", 120.0))

# Share moves below this are rounding noise, not a trade.
_SHARE_EPS: float = 0.01


class WalletReconciler:
    """
    Periodically checks that on-chain inventory only moves when the bot thinks
    it is trading.  Read-only: it never places or cancels an order.
    """

    def __init__(
        self,
        client:   "PolyClient",
        breaker:  "CircuitBreaker",
        notifier: "TelegramNotifier",
        poll_s:   float = RECONCILE_POLL_S,
    ) -> None:
        self._client   = client
        self._breaker  = breaker
        self._notifier = notifier
        self._poll     = max(10.0, poll_s)
        self._prev: dict[str, float] | None = None
        self._prev_cash: float | None = None
        self.unexplained_events: int = 0
        logger.info("WalletReconciler init | poll=%.0fs", self._poll)

    # ──────────────────────────────────────────────────────────────────────────

    async def _snapshot(self) -> "tuple[dict[str, float], float] | None":
        rows = await self._client.open_positions_detail()
        if rows is None:
            return None
        cash = await self._client.collateral_balance()
        if cash is None:
            return None
        held = {
            f"{r.get('title','')[:40]}|{r.get('outcome','')}": float(r.get("size") or 0.0)
            for r in rows
        }
        return held, float(cash)

    async def check_once(self) -> "dict | None":
        """
        One comparison. Returns a report dict when inventory moved with nothing
        open, else None.
        """
        snap = await self._snapshot()
        if snap is None:
            logger.debug("WalletReconciler | snapshot unavailable — skipping")
            return None
        held, cash = snap

        if self._prev is None:
            self._prev, self._prev_cash = held, cash
            logger.info(
                "WalletReconciler | baseline: %d position(s), cash=%.4f",
                len(held), cash,
            )
            return None

        moves = {
            k: round(held.get(k, 0.0) - self._prev.get(k, 0.0), 4)
            for k in set(held) | set(self._prev)
        }
        moves = {k: v for k, v in moves.items() if abs(v) > _SHARE_EPS}
        cash_delta = round(cash - (self._prev_cash or cash), 4)
        self._prev, self._prev_cash = held, cash

        if not moves:
            return None

        open_positions = int(self._breaker.status_dict().get("open_positions", 0))
        if open_positions > 0:
            # Normal: something is in flight and is expected to move inventory.
            logger.debug(
                "WalletReconciler | %d move(s) with %d position(s) open — expected",
                len(moves), open_positions,
            )
            return None

        # Inventory moved while the bot believed it had nothing open.
        self.unexplained_events += 1
        report = {
            "moves": moves,
            "cash_delta": cash_delta,
            "open_positions": open_positions,
        }
        detail = ", ".join(f"{k} {v:+.2f}" for k, v in sorted(moves.items()))
        logger.error(
            "RECONCILE | inventory moved with NOTHING open — an order escaped "
            "supervision | cash %+.4f | %s",
            cash_delta, detail,
        )
        await self._notifier.notify(
            "⚠️ RECONCILE — inventory changed while the bot had nothing "
            f"open.\ncash {cash_delta:+.4f} pUSD\n{detail}\n"
            "An order filled outside guard supervision; check for resting orders."
        )
        return report

    async def run(self) -> None:
        logger.info("WalletReconciler started | poll=%.0fs", self._poll)
        try:
            while True:
                await asyncio.sleep(self._poll)
                try:
                    await self.check_once()
                except asyncio.CancelledError:
                    raise
                except Exception as exc:  # noqa: BLE001
                    logger.error("WalletReconciler check failed: %s", exc)
        except asyncio.CancelledError:
            logger.info("WalletReconciler stopped")
            raise
